apiVersion: v1
kind: Service
metadata:
  name: ps-settings-ui-service
  labels:
    app: ps-settings-ui-service
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 80
      nodePort: 32001
  type: LoadBalancer
  selector:
    app: ps-settings-ui

