apiVersion: v1
kind: Service
metadata:
  name: ps-settings-api-db-service
  labels:
    app: ps-settings-api-db-service
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  type: ClusterIP
  selector:
    app: ps-settings-api-db