apiVersion: apps/v1
kind: Deployment
metadata:
  name: settings-api-db-deployment
  labels:
    app: ps-settings-api-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ps-settings-api-db
  template:
    metadata:
      labels:
        app: ps-settings-api-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: settings_db
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres
          image: postgres:13.3
          name: ps-settings-api-db
          ports:
            - containerPort: 5432
